### ISSUE TITLE
Media device can not be created. Not all states are in gui

### ISSUE THREAD

**Issue by britzelpuf** [ioBroker/ioBroker.devices#152] opened 2022-03-17 21:06 UTC
**Describe the bug**  
When I create a media alias only the ACTUAL state will be created in the gui.
And I think there should be more states than that. 

**To Reproduce**  
1. goto Devices
2. Click on '+'
3. Add media device
<img width="643" alt="image" src="https://user-images.githubusercontent.com/101716456/158878947-8914c33f-6198-4afb-9a51-03171cb68312.png">
4. Click on states
Only ACTUAL
<img width="634" alt="image" src="https://user-images.githubusercontent.com/101716456/158879072-3962ecdb-b414-4c57-bcb6-cbf65f71c5d8.png">

Log says that the javascript adapter has an error:
<img width="698" alt="image" src="https://user-images.githubusercontent.com/101716456/158880345-72da7798-d4f7-4b69-8cbf-45a0599520a2.png">

**Expected behavior**  
States mentioned in the  index.js [A](https://github.com/ioBroker/ioBroker.type-detector/blob/69ee803b594b1887af78f107d5437e2afb0f3c73/index.js#L120) should be available.

**Versions:**  
 - Adapter version:  v1.0.10,
 - JS-Controller version: 3.3.22
 - Node version: v14.19.0
 - Operating system: buanet/iobroker:latest

**Comment by Garfonso** [comment] 2022-09-30 12:05
Still is an issue.

**Comment by Garfonso** [comment] 2022-10-01 06:01
also duplicate of #140

**Closed** 2022-12-28 13:12 UTC
